TelegramAccounts = { 1: {"Name": "bot1",
                         "API": '',
                         "ID": '-100'},
                     2: {"Name": "Scalp",
                         "API": '',
                         "ID": '-100'},
                     3: {"Name": "Swing",
                         "API": '',
                         "ID": '-100'}
                   }
Accounts = { 1: {"Name": "Bot1",
                 "EXCHANGE": "ftx",
                 "EXCHANGEAPI": '',
                 "EXCHANGESECRET": '',
                 'Subaccount': 'No',
                 'SubName': 'None',
                 'UseTwitter': 'No',
                 'UseTelegram': 'Yes',
                 'Track': 'Yes'},
             2: {"Name": "Swing",
                 "EXCHANGE": "ftx",
                 "EXCHANGEAPI": '',
                 "EXCHANGESECRET": '',
                 'Subaccount': 'Yes',
                 'SubName': 'Swing',
                 'UseTwitter': 'Yes',
                 'UseTelegram': 'Yes',
                 'Track': 'No'}
            }
twitter = {'ConsumerKey': '',
           'ConsumerSecret': '',
           'AccessToken': '',
           'AccessSecret': ''}
